version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    ports:
      - "3306:3306"
  # db_admin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   links:
  #    - db:db
  #   ports:
  #     - "8080:80"

  omeka-s:
    depends_on:
      - db
    build: ./
    image: qcifengineering/omeka-s
    ports:
      - "8080:80"
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/custom/:/var/www/html/themes/custom/
    restart: always
